### ISSUE TITLE
Suggestion Install Script.

### ISSUE THREAD

**Issue by red0fireus** [wofferl/proxmox-backup-arm64#37]
Server Install:

sudo apt install $(find . -type f \
  \( -name "libjs-extjs_*_all.deb" \
  -o -name "libjs-qrcodejs_*_all.deb" \
  -o -name "libproxmox-acme-plugins_*_all.deb" \
  -o -name "pbs-i18n_*_all.deb" \
  -o -name "proxmox-backup-docs_*_all.deb" \
  -o -name "proxmox-backup-server_*_arm64.deb" \
  -o -name "proxmox-mini-journalreader_*_arm64.deb" \
  -o -name "proxmox-widget-toolkit_*_all.deb" \
  -o -name "pve-xtermjs_*_arm64.deb" \))

Error: N: Download is performed unsandboxed as root as file '/root/proxmox-backup-arm64/packages/proxmox-backup-docs_3.0.2-1_all.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)

Potential Fix:
chmod -R o+r /root/proxmox-backup-arm64/packages/

**Comment by red0fireus** [comment]
This script will find the latest build version.

**Comment by wofferl** [comment]
> Error: N: Download is performed unsandboxed as root as file '/root/proxmox-backup-arm64/packages/proxmox-backup-docs_3.0.2-1_all.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)

The problem is that you downloaded or build the packages in the home directory of the root user /root

apt uses the internal _apt user when installing files. This user has no access to /root and its subdirectories. 
To fix this the packages folder needs to be in a place where the _apt user has access to.
