### ISSUE TITLE
proxmox-backup-proxy is missing libsgutils2-1.45.so.2 on ubuntu

### ISSUE THREAD

**Issue by der-graph** [wofferl/proxmox-backup-arm64#38]
Hi,

after some os and pbs updates to the latest 2.4 release proxmox-backup-proxy couldn't start anymore. Because of this I upgraded to the new unofficial 3.0-x release and the problem continued to exist.
The log was showing a missing libsgutils2-1.45.so.2. Ubuntu says there is already the newest libsgutils2-1.46 installed. At the moment i did a dirty symlink fot libsgutils2-1.45.so.2 to libsgutils2-1.46.so.2 and pbs is running again.

Ubuntu problem with the lib?

Daniel

**Comment by wofferl** [comment]
There is a change for the libsgutils2 dependencies between the old and new distributions. In debian this change was between bullseye and bookworm, where the dependency changed from ibsgutils2-2 to libsgutils2-1.46-2.

Did you use the build script to compile the proxmox-backup packages or did you download the pre compiled?
Which Ubuntu Version do you have?

The pre compiled packages are compiled for bullseye and should be running on ubuntu 22.04 (jammy).
If you want them on ubuntu 23.04, you need to compile them by yourself.

**Comment by wofferl** [comment]
> But if I delete the symlink I get:
> 
> proxmox-backup-proxy: error while loading shared libraries: libsgutils2-1.45.so.2: cannot open shared object file: No such file or directory

The problem here is that libsgutils doesn't have symlinks without version. That seems the reason, that in Debian/Bookworm the libsgutils package changed the dependency name.

ldd /usr/lib/aarch64-linux-gnu/proxmox-backup/proxmox-backup-proxy
`libsgutils2-1.45.so.2 => /lib/aarch64-linux-gnu/libsgutils2-1.45.so.2 (0x0000ffff8fbca000) `

This is not optimal and I hope that the maintainers of libsgutils will change this in the future.

**Comment by der-graph** [comment]
I see, thank you for your explanation.

Just for clarification: this means if you compile the packages again by yourself on ubuntu the problem is gone anyway?

**Comment by wofferl** [comment]
Yes, it links to the installed version of libsgutils2. Normally that is no big problem, because libsgutils2 isn't updated that much, but in this case it makes packages in debian that relies on this package incompatible with ubuntu.

But if you have libssl1.1 installed you can try to go with the symlink. From the libsgutils changelog I don't see any critical changes in 1.46, so it should be safe to use.

**Comment by der-graph** [comment]
ok, thanks again for pointing this out and for your time and effort.
