### ISSUE TITLE
Unable to complete install - Make issue

### ISSUE THREAD

**Issue by Jarvis-1487** [wofferl/proxmox-backup-arm64#4]
`warning: build failed, waiting for other jobs to finish...
error: build failed
make[2]: *** [Makefile:172: .do-cargo-build] Error 101
make[2]: Leaving directory '/home/pi/proxmox-backup-arm64/sources/proxmox-backup'
dh_auto_build: error: make -j4 "INSTALL=install --strip-program=true" PROXY_USER=backup LIBDIR=/usr/lib/aarch64-linux-gnu returned exit code 2
make[1]: *** [debian/rules:28: override_dh_auto_build] Error 2
make[1]: Leaving directory '/home/pi/proxmox-backup-arm64/sources/proxmox-backup'
make: *** [debian/rules:21: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
`

Might be a simple fix but I have tried this on DietPi and Raspi OS and the build fails at the same point every time. Thanks for your effort in compiling this! Would love to get it working, do you have any advice on what's wrong? TIA

**Comment by MAFLO321** [comment]
Looks like an error in the cargo build process...

- I guess you used the 64-bit images with "Debian" bullseye of Raspberry Pi OS and DietPi?
- Could you provide a full log or something (just upload it to your favorite pastebin, gist or cloud site)?
   ```bash
   # for example
   ./build.sh 2>&1 | tee build.log
   ```

**Comment by Jarvis-1487** [comment]
https://pastebin.com/Pmuei2iL

Hopefully this helps!?

Should I try the 32 bit instead?

**Comment by MAFLO321** [comment]
I am not 100% sure, but for me it indicates the following:
- The build process aborted at the linker (`ld`) because it was killed externally.
- Normally the linking process uses a lot of memory (RAM).This could lead to the Linux Out of Memory (OOM) killer terminating the process with SIGKILL (signal 9) because there is no more free memory available.
This could lead to the Linux Out of Memory (OOM) killer terminating the process with SIGKILL (signal 9) because there is no more free memory available.
- To check this you could use `sudo journalctl -e` and then type `?` (reverse search) and then `Killed` and press enter, with `n` you can jump to the next result. You should find something like the pictures on this [site](https://support.hypernode.com/en/troubleshooting/performance/how-to-debug-out-of-memory-oom-events#Debug-OOM-Events) under " Debug OOM Events".
- How to work around this problem? More RAM (4 or 8 GB) or increase swap. Raspberry Pi OS uses `dphys-swap` for swap ([short guide](https://raspiserver.com/how-to-increase-swap-on-raspberry-pi/)). I don't know how DietPi does it, swapfile or swappartition.

Which Rasberry Pi do you have with how much RAM an SWAP configuration?
For me it builds on my Odroid n2 with 4GiB RAM + 4 GiB (zswap -> compressed ram).

**Comment by MAFLO321** [comment]
@wofferl Should we add some GitHub Actions for building releases and uploading them to the release page?
I'm not sure if this is a good idea, because then people witch are not so familiar use this project and maybe run into problems and can't handle them by themselves and no-one will be there to help them. This is especially bad if this happens for a software which hold's your backups. Or am I too pessimistic? :rofl:

**Comment by Jarvis-1487** [comment]
It did seem to hang. I have a Pi 4 4GB so I will give it a go by increasing the swap size. 

Really appreciate your help guys, I wish I was this smart to be able to compile it myself for Arm64! :1st_place_medal:

**Comment by wofferl** [comment]
@MAFLO321 If you release binary packages, you should also ensure that everything works. So I don't think it's a good idea to release packages. If someone has problems compiling the packages, you can always offer to provide them with the packages somehow.

**Comment by MAFLO321** [comment]
@Jarvis-1487 did it work for you?
If yes, what was your configured swap size? And close the issue, please.

**Comment by Jarvis-1487** [comment]
No I added an SSD to my 4GB Pi4 and gave it 8GB of swap but it still failed to build. I found an old intel laptop lying around so installed PBS on that instead. Its a shame though, would have been nice to get it running on my Pi. 
I noticed the first official release of the RPi 64bit image got released on Wednesday so may give it another go! 
Sorry to leave this hanging, I will close the issue.
